import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/Navs/MainNav";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FootballApi Training",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${montserrat.className}`}>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
