import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/Navs/MainNav";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FootballApi Training",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${montserrat.className}`}>
        <header>
          <MainNav />
        </header>
        <main className='flex pt-[125px] items-start max-w-[1280px] justify-evenly mx-auto'>
          {children}
        </main>
      </body>
    </html>
  );
}
